### PR TITLE
Add subsets for montserrat font-family to include "→" character

### LINKED ISSUE #91: Montserrat: the “→” character is rendered in a fallback font
Here’s how https://3perf.com looked [back in May 2022](http://web.archive.org/web/20220514020900/https://3perf.com/):

CleanShot 2022-09-28 at 22 04 06@2x

Here’s how it looks right now:

Screen Shot 2022-09-28 at 22 04 39

A few things have changed:

* the “→” character that was previously rendered in Montserrat is now rendered in `sans-serif` and looks differently
* ~~the “New article:” text is rendered in Montserrat Black (aka `font-weight: 900`), whereas it should be Montserrat Bold (aka `font-weight: 700`)~~ (fixed)

All of these changes have likely happened due to #89. We should fix them:
* The first issue has happened because the Google Fonts version of Montserrat, apparently, doesn’t include the “→” character. (Try going to https://fonts.google.com/specimen/Montserrat/tester and pasting that character in.)

  We can work around this e.g. by converting that arrow into an SVG icon and adding it straight into the HTML. (Please make sure to also add an appropriate [`aria-label`](https://gomakethings.com/icon-accessibility-and-aria-label/).)

* ~~No idea what caused the second one. (Did we include Montserrat Bold from `@fontsource`?)~~ (Yeah, that’s precisely what happened)

### PR DESCRIPTION
**Pull request by vadikmash**
Closes #91.

----

Used [glyphhanger](https://github.com/zachleat/glyphhanger) tool (version 5.0.0) to create subsets. To subset fonts in the future, please use the following commands:
```zsh
# Installation
npm install -g glyphhanger
# Additional installation for working with woff2 format
pip install brotli

# Usage
glyphhanger --subset="*.woff2" --formats=woff2 --LATIN --whitelist=→      
```
This would create font subsets for all `.woff2` fonts and output them in the same format with `-subset` postfix. It would also output unicode ranges, that you can use in your `@font-face` declarations in css.

-----

To prevent unnecessary loading of fallback non-subset fonts on pages with certain types of emoji, I've used the following tools:
- [emoji-unicode-range](https://github.com/fraction/emoji-unicode-range) to get current unicode range for emoji.
- [Unicode Range Interchange](https://www.zachleat.com/unicode-range-interchange/) to exclude emoji unicode range from fallback non-subset fonts declarations.

Current emoji unicode range: [emoji-unicode-range.txt](https://github.com/3perf/website/files/10147001/emoji-unicode-range.txt).

### CODE REVIEW

**Comment by iamakulov** [comment]
Darn, this is great!

Qq: while testing on the home page, I noticed that the full “Bold” font is downloaded in addition to the subsetted one:

Screenshot 2022-11-29 at 23 53 48

(See rows 3 and 4.)

Is there anything we can do to optimize this? 
* Re-subset Montserrat to include missing characters?
  * But what are these characters? May this be due to emojis on the page? (In the past, once or twice, I’ve seen `glyphhanger` log warnings about emojis, saying that emojis would cause the full font to download because they aren’t covered by specified `unicode-range`s.)
  * If this is due to emojis, we’ll probably have to
    * wrap them with `<span style="font-family: sans-serif">`
    * or find a way to do the above automatically
    * (perhaps the easiest approach) or make the `unicode-range` in `@font-face` cover only the actual glyphs the font supports, not `U+0-FFFF`. For this, tools like https://wakamaifondue.com/ (use it to see supported glyphs) or https://www.zachleat.com/unicode-range-interchange/ (use it to add/substract unicode ranges) might be useful
* Subset the full font to only include non-latin characters so it’s smaller?
* (Any other things we could do?)

**Comment by vadikmash** [comment]
@iamakulov, hey!

I've fixed fallback non-subsetted fonts loading issue by excluding emoji unicode range from fallback `@font-face` declarations.
image
Also, updated PR description with more detailed explanation of how I did it and instructions for further font subsetting. Lmk if I missed anything or if you need more descriptive instructions.

**Review by iamakulov — APPROVED** [review]
This is amazing! Thank you especially for fixing the emoji issue.

**Comment by iamakulov** [comment]
Gah, the builds are now failing due to https://answers.netlify.com/t/builds-failing-because-they-started-using-npm-instead-of-yarn/79495. Will merge this in a couple days (hopefully the issue is fixed by that date).

**Comment by vadikmash** [comment]
@iamakulov, looks like Netlify checks have been fixed!

**Pull request merged**
