### PR TITLE
Update gatsby-image to gatsby-plugin-image #58

### LINKED ISSUE #58: Update gatsby-image to gatsby-plugin-image
Currently, to load images, we use [`gatsby-image`](https://www.gatsbyjs.com/plugins/gatsby-image/). However, it was deprecated, and it’s now recommended to use [`gatsby-plugin-image`](https://www.gatsbyjs.com/plugins/gatsby-plugin-image) instead.

It would be great to upgrade to `gatsby-plugin-image`. Here’s the migration guide: https://www.gatsbyjs.com/docs/reference/release-notes/image-migration-guide/

### PR DESCRIPTION
**Pull request by vadikmash**
Closes #58.

Fully migrated to `gatsby-plugin-image`. Everything seems to look exactly as before, except for new beautifully animated image loading.
I've highly simplified `Image` component, so you should probably take a closer look and decide, whether it was a right thing to do.

### CODE REVIEW

**Comment by iamakulov** [comment]
> I've highly simplified Image component, so you should probably take a closer look and decide, whether it was a right thing to do.

That’s great, thank you! `gatsby-image` didn’t work well with `gatsby-plugin-no-javascript` which was the reason we needed a custom image implementation. `gatsby-plugin-image` seems to work with `gatsby-plugin-no-javascript` perfectly, so this is a really nice improvement.

**Comment by iamakulov** [comment]
> `gatsby-plugin-image` seems to work with `gatsby-plugin-no-javascript` perfectly, so this is a really nice improvement.

Gah, no, it actually doesn’t. In Safari, images stay invisible.

<details>

<summary>Why?</summary>

The way the new `gatsby-plugin-image` works is it generates a bunch of inline scripts that load the image:

Screen Shot 2022-01-14 at 14 08 38

and add a nice transition when the image loads:

Screen Shot 2022-01-14 at 14 09 22

For some reason, these scripts bail out early and don’t run if the browser doesn’t support native image lazy loading. (See `const t="undefined"!=typeof HTMLImageElement&&"loading"in HTMLImageElement.prototype;if(t){...}` in the beginning of each script.) Safari doesn’t, so these scripts don’t run, and images stay invisible.

On a typical site, I presume, what happens next is the bundle loads, fixes these images, and makes the browser load them even in Safari. However, because we use `gatsby-plugin-no-javascript`, no bundle loads, and no images are fixed. 

</details>

I suggest to revert back to a custom `<Image>` implementation. Gatsby’s one still brings more issues than it solves :/

**Review by iamakulov — CHANGES_REQUESTED** [review]
(See above.)

**Comment by iamakulov** [comment]
@vadikmash Heya – let me know if you need any help with finishing this! (Don’t hesitate to reach out if you feel stuck.)

Re: webp in Safari – I’m actually comfortable with using webp there. Safari [supports it as of v14 (and macOS Big Sur)](https://caniuse.com/webp), and I don’t care much about older OSes/versions.

**Comment by vadikmash** [comment]
Hey! I've updated new code to be compatible with `gatsby-image-plugin`.
Good news. It looks like `GatsbyImage` implementation works correctly in Safari now! All images are visible.

**Review by iamakulov — COMMENTED** [review]
Perfect, thanks so much 🔥 Can confirm images work fine in Safari.

Noticing two issues (they are localized – but the root issues are likely deeper):

**1\) Outdated content**

I see you merged `master` into the current branch – however, the content on the home page appears to be outdated in the PR preview. Compare e.g. the end of the page on https://3perf.com (no mention of “Chris”):

Screen Shot 2022-08-02 at 21 31 58

and in the PR preview (“Chris” mentioned):

Screen Shot 2022-08-02 at 21 32 16

Is there any chance merging an outdated `master` into this branch accidentally brought some old changes?

**2\) Round/square image**

In the PR preview, one of the avatars has square corners (and lives on a separate line):

CleanShot 2022-08-02 at 21 34 02@2x

I believe I encountered something similar before. So, to perhaps save the research time – is this something about `gatsby-plugin-image` rendering a `div`? Browsers dislike when there’s a `<div>` inside a `<p>` (it’s considered invalid markup), so this may be what’s happening here.

In general, there are a couple tricky image places that need double-checking:
- avatars in the end of the home page (if something’s configured incorrectly, they might be square, like above)
- images at https://3perf.com/talks/web-perf-101/#js-code-splitting-2 – if the `display` value on the image wrapper goes off, the image might get a white space beneath it, like here:

   CleanShot 2022-08-02 at 21 41 11@2x

   (This is not currently an issue but might happen with changes to images.

**Comment by vadikmash** [comment]
Soo.. I've fixed all the issues. Had to apply some inline styles to `GatsbyImage` component, which were the only way to properly style image container and image itself according to [documentation](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/#shared-props) (replacing `div` container element with `span` did not help). Hope that this solution is acceptable :)

**Comment by iamakulov** [comment]
Wonderful ⚡ Thank you!

**Review by iamakulov — APPROVED** [review]

**Pull request merged**
